/* Private SDL events from Cocoa panels to the guest input loop. */
#ifndef HALO_MACOS_NATIVE_EVENTS_H
#define HALO_MACOS_NATIVE_EVENTS_H
#define HALO_MACOS_MOUSE_RELEASE 0x48414c01
#define HALO_MACOS_DISPLAY_WINDOWED 0x48414c02
#define HALO_MACOS_DISPLAY_BORDERLESS 0x48414c03
#endif
